### ISSUE TITLE
Compatibility with plotly package in R 

### ISSUE THREAD

**Issue by boefraty74** [ramnathv/htmlwidgets#271] opened 2017-04-29 09:53 UTC
Hi, 
The existing code to save plotly object as HTML stopped working with last package of plotly in CRAN. 
Here is toy-example. 

library(plotly)
library(htmlwidgets)
set.seed(100)
d <- diamonds[sample(nrow(diamonds), 1000), ]
p <- ggplot(data = d, aes(x = carat, y = price)) +
  geom_point(aes(text = paste("Clarity:", clarity)), size = 4) 
gg <- ggplotly(p)

**htmlwidgets::saveWidget(gg, file = "index.html")**

**Comment by jjallaire** [comment] 2017-04-29 10:17
@cpsievert Any idea why this may be happening?

**Comment by cpsievert** [comment] 2017-05-01 00:43
Works for me...could you clarify what you mean by stopped working @boefraty74?

**Comment by boefraty74** [comment] 2017-05-01 06:55
Hi, 
You should remove plotly package and install the last one. 

> htmlwidgets::saveWidget(gg, file = "index.html")
Error in system.file(config, package = package) : 
  'package' must be of length 1

**Comment by boefraty74** [comment] 2017-05-01 07:10
Hi @cpsievert and @ jjallaire 
I do not know where is exactly the problem, to reproduce it need I had to remove all packages and  install.packages from CRAN to be latest ones.

**Comment by ramnathv** [comment] 2017-05-01 11:15
It would be useful to provide `sessionInfo()` so we know what versions of the packages you have installed.

**Comment by cpsievert** [comment] 2017-05-01 15:13
@boefraty74 does the same problem occur when trying to save other widgets? For example, `leaflet::leaftet()`?

**Comment by cpsievert** [comment] 2019-03-22 21:40
Closing due to lack of a reproducible example

**Closed** 2020-09-04 17:53 UTC
