### ISSUE TITLE
Not able to automatically download Bower packages

### ISSUE THREAD

**Issue by nuno-agostinho** [ramnathv/htmlwidgets#186] opened 2016-02-12 16:08 UTC
The scaffoldWidget is having issues downloading packages from Bower, throwing the following error:

``` R
htmlwidgets::scaffoldWidget("cesium", bowerPkg = "cesiumjs")
## Created boilerplate for widget constructor R/cesium.R
## Error in if (findBower() == "") { : argument is of length zero
```

No matter the package I choose, the error is always the same.

**Comment by ramnathv** [comment] 2016-02-12 23:18
It seems like either you dont have bower installed, or your R installation is not able to find its location. Can you run `which bower` in your command line and also `system("which bower")` in your R console. That should give some clues as to what the problem is.

**Comment by nuno-agostinho** [comment] 2016-02-12 23:48
It seems I didn't have bower correctly installed so I've reinstalled it and htmlwidget's working as expected. I think it'd be nice to present what you said as an error message instead of the error I got. Many thanks for your help!

**Comment by ramnathv** [comment] 2016-11-22 21:36
Closing this, since you were able to resolve it @nuno-agostinho.

**Closed by ramnathv** 2016-11-22 21:36 UTC
