### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by asmeurer** [ramnathv/htmlwidgets#101] opened 2015-04-24 15:46 UTC
Can you tag release(s) (at the very least the latest release)? It will make it easier to build a conda package, especially since the latest version on CRAN doesn't work with rbokeh.

**Comment by ramnathv** [comment] 2015-04-24 18:05
That is strange, since @hafen confirmed that `rbokeh` works with the updates made to `htmlwidgets`. In any case, what you are suggesting is a good idea and we will tag releases made in the future. Thanks for the suggestion.

**Comment by ramnathv** [comment] 2015-04-24 18:09
Ah okay. I realize that the CRAN version is still at `0.3.2`. @jjallaire what is our timeline to push out `0.3.3` to CRAN. In the interim, I think @hafen can tag a release of `rbokeh` that works with the current CRAN version.

**Comment by asmeurer** [comment] 2015-04-24 18:12
I am getting

```
> library(rbokeh)
> p <- figure() %>%
+   ly_points(Sepal.Length, Sepal.Width, data = iris,
+     color = Species, glyph = Species,
+     hover = list(Sepal.Length, Sepal.Width))
p
Error in htmlwidgets::createWidget(name = "rbokeh", x = list(spec = spec,  :
  unused argument (preRenderHook = rbokeh_prerender)
```

with the CRAN version of htmlwidgets.

**Comment by ramnathv** [comment] 2015-04-24 18:28
@asmeurer The `preRenderHook` function was added to `htmlwidgets` in `0.3.3` which is not on CRAN yet. @hafen updated the `rbokeh` repo to work with `0.3.3` and so his latest release rbokeh `0.2.2` works with htmlwidgets `0.3.3`. If @hafen can tag a release that is consistent with the CRAN version, then it can solve the problem in the interim, till we get 0.3.3 on CRAN.

**Comment by asmeurer** [comment] 2015-04-24 18:45
Thanks, that should work.

**Comment by hafen** [comment] 2015-04-24 20:40
I just tagged 0.2.1 which should work with CRAN htmlwidgets.

**Comment by jjallaire** [comment] 2015-04-24 22:36
As long as there aren't any other major changes in the pipeline we can do a
release now. Let me know if I should be waiting for anything that imminent.

Do we need to bump any of the versions of our dependencies? (e.g. htmltools)

**Comment by ramnathv** [comment] 2015-04-24 23:53
Thanks @jjallaire. I need to clean up a few PRs on iframe support and file dependencies. I can turn it around this weekend, and have it reviewed next week. We can shoot for a CRAN release in the first half of May if everyone is agreeable to that.

**Comment by jjallaire** [comment] 2015-04-24 23:55
Sounds good to me!

**Comment by jcheng5** [comment] 2015-04-25 03:16
I believe we have to sync up the release with the next shiny CRAN release
as well. cc @yihui
>
>

-- 
Sent from my phone

**Comment by ramnathv** [comment] 2015-04-25 06:43
That makes sense @jcheng5. Since @hafen has tagged a release consistent with the CRAN version of `htmlwidgets`, we are in no hurry to get this update up on CRAN.

**Comment by yihui** [comment] 2015-04-25 14:28
Yes, the next version of htmlwidgets should be released together with the next version of shiny (only for this time).

Regarding the git tags, I see there are currently no tags in this repo. There is only a branch named v0.3.2-CRAN. I'd suggest use tags instead of branch names, and the tags are of the form `vx.y.z` (or `x.y.z`), e.g. `git tag v0.3.2`. Since the JSON stuff is a relatively big change, I think it is reasonable to make the next CRAN version number 0.4 or something instead of 0.3.3 (which sounds like a very minor update).

**Comment by ramnathv** [comment] 2015-04-25 16:30
That makes sense @yihui. I will be wrapping up my PRs on iframe support and file dependencies, and will update version to 0.4 once they are reviewed and merged. We will also follow the tagging scheme you have proposed here.

**Comment by ramnathv** [comment] 2015-08-13 22:39
I am closing this as all packages are in sync now.

**Closed by ramnathv** 2015-08-13 22:39 UTC

**Comment by asmeurer** [comment] 2015-08-25 20:03
Note that the original issue was not fixed (there are no tags here https://github.com/ramnathv/htmlwidgets/releases).
